"""initial

Revision ID: 9dd8d81ac12f
Revises: 
Create Date: 2023-03-26 04:24:42.552029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dd8d81ac12f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bags",
        sa.Column("bag_id", sa.UUID(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("bag_id"),
        sa.UniqueConstraint("bag_id"),
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("customer_first_name", sa.String(length=255), nullable=False),
        sa.Column("customer_last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phonenum", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("bag_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("customer_id"),
        sa.UniqueConstraint("bag_id"),
        sa.UniqueConstraint("customer_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("order_id"),
        sa.UniqueConstraint("phonenum"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("bag_id", sa.UUID(), nullable=True),
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=2, decimal_return_scale=2),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("order_id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column(
            "product_price",
            sa.Numeric(precision=12, scale=2, decimal_return_scale=2),
            nullable=False,
        ),
        sa.Column("product_left", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
        sa.UniqueConstraint("product_id"),
        sa.UniqueConstraint("product_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("orders")
    op.drop_table("customers")
    op.drop_table("bags")
    # ### end Alembic commands ###
