"""models

Revision ID: b0d0ea1b7dd2
Revises: 58da6be27401
Create Date: 2023-03-26 04:32:07.820584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d0ea1b7dd2'
down_revision = '58da6be27401'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.add_column('bags', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'bags', ['bag_id'])
    op.create_foreign_key(None, 'bags', 'products', ['product_id'], ['product_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bags', 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'customers', ['customer_id'])
    op.create_foreign_key(None, 'customers', 'orders', ['order_id'], ['order_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customers', 'bags', ['bag_id'], ['bag_id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'orders', ['order_id'])
    op.create_foreign_key(None, 'orders', 'bags', ['bag_id'], ['bag_id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'products', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'bags', type_='foreignkey')
    op.drop_constraint(None, 'bags', type_='foreignkey')
    op.drop_constraint(None, 'bags', type_='unique')
    op.drop_column('bags', 'product_id')
    op.drop_column('bags', 'customer_id')
    # ### end Alembic commands ###
